[workspace]
members = [
    "libstamp",
    "stamp",
    "stamp-plugin-sdk"
]
resolver = "2"

[workspace.lints.rust]
missing_docs = "deny"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)', 'cfg(tarpaulin_include)'] }

[workspace.lints.clippy]
all = { level = "deny", priority = -2 }
pedantic = { level = "deny", priority = -1 }
unwrap_used = "deny"
expect_used = "deny"
doc_markdown = "allow"
cast_possible_truncation = "allow"
missing_errors_doc = "allow"
redundant_closure_for_method_calls = "allow"
struct_excessive_bools = "allow"
must_use_candidate = "allow"
module_name_repetitions = "allow"
similar_names = "allow"
too_many_lines = "allow"
collapsible_if = "allow"
unnecessary_map_or = "allow"
case_sensitive_file_extension_comparisons = "allow"
cast_precision_loss = "allow"
cast_sign_loss = "allow"
needless_raw_string_hashes = "allow"
items_after_statements = "allow"
field_reassign_with_default = "allow"
unreadable_literal = "allow"
needless_continue = "allow"
unused_async = "allow"
unused_async_trait_impl = "allow"
default_constructed_unit_structs = "allow"
manual_assert_eq = "allow"
manual_let_else = "allow"
